import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const LANGUAGES = {
  en: 'English', hi: 'हिन्दी', ta: 'தமிழ்', te: 'తెలుగు'
};

const base = {
  command:'Command', dashboard:'Dashboard', newCase:'New Case', cases:'Cases', appeals:'Appeals', active:'System Active', language:'Language',
  heroEyebrow:'INDIA · CIVIC INTELLIGENCE / 01', heroTitle1:'Resolve', heroTitle2:'bureaucracy.', heroTitle3:'Systematically.', heroAccent:'',
  heroLead:'CivivOS turns a civic problem into a visible path — with reasoning, documents, deadlines and the next action always in view.', startCase:'Start a Civic Case', continueCase:'Continue last case', workflowFirst:'WORKFLOW FIRST · EVIDENCE ALWAYS',
  monitor:'LIVE SYSTEM MONITOR', monitorText:'The case engine classifies, drafts, watches and escalates the matter.', principle:'THE CIVIVOS PRINCIPLE / 02', principleTitle:'A civic problem should have a state.', principleText:'A next action. A responsible authority. And a record that does not disappear when the citizen leaves.',
  how:'HOW CIVIVOS WORKS / 03', howTitle:'From complaint to civic action.', howText:'CivivOS turns an unstructured complaint into a traceable workflow. Every stage has a state, an artifact and a next decision.',
  steps:['Describe the problem','Classify the issue','Choose the route','Prepare the document','Watch the deadline','Escalate when required'],
  intelligence:'CIVIVOS / INTELLIGENCE', intelligenceTitle:'Make bureaucracy legible.', intelligenceText:'The system reasons about the complaint, prepares the route and keeps the case state visible instead of leaving the citizen to guess what happens next.', understand:'Understand the system',
  newCaseKicker:'NEW CASE / 01', newCaseTitle:'Tell CivivOS what happened.', newCaseIntro:'Describe the civic problem in your own words. CivivOS will classify it, determine a legal route, and prepare the next civic action.', citizenName:'Citizen name', whatHappened:'What happened?', namePlaceholder:'Your name', complaintPlaceholder:'Describe the delay, denial, missing service or unanswered application...', persistent:'Your case becomes a persistent civic record.', createCase:'Create Case', analyzing:'Analyzing…',
  casePath:'CASE PATH / 02', auditTrail:'AUDIT TRAIL / 03', currentState:'CURRENT STATE', nextAction:'NEXT ACTION', approve:'Approve Draft', file:'File Case', monitorResponse:'Start Monitoring', runWatcher:'Run Watcher', openAppeal:'Open First Appeal', firstAppealReady:'The first appeal is ready.', firstAppealNotReady:'The first appeal is not ready.', returnCase:'Return to Case',
  systemActive:'SYSTEM ACTIVE', india:'INDIA', state:'STATE', action:'ACTION', record:'RECORD',
  attention:'ATTENTION', needsAttention:'YOUR NEXT DECISION', noneAttention:'Nothing needs your attention right now.', activeCases:'ACTIVE CASES', needsAction:'NEEDS YOUR ACTION', governmentReview:'UNDER GOVERNMENT REVIEW', yourCases:'YOUR CASES', everyMatter:'Every matter. One visible path.', doing:'WHAT CIVIVOS IS DOING', doingTitle:"The system doesn't stop at filing.", responseWatch:'RESPONSE WATCH', nextDeadline:'YOUR NEXT DEADLINE', noActiveDeadline:'No active deadline.', principleQuote:'A civic problem should have a state, a next action, and a record of what happened.',
  readyAction:'ACTION READY', loading:'Reading your civic record…', error:'Something went wrong.',
  stateLabels:{CREATED:'Created',ANALYZING:'AI Analysis',DRAFT_READY:'Draft Ready',WAITING_APPROVAL:'Approval Required',CITIZEN_APPROVED:'Approved',FILED:'Filed',WAITING_RESPONSE:'Government Response',FIRST_APPEAL_REQUIRED:'First Appeal Required',CLOSED:'Closed'}
};

const hi = {...base, command:'कमांड', dashboard:'डैशबोर्ड', newCase:'नई शिकायत', cases:'केस', appeals:'अपील', active:'सिस्टम सक्रिय', language:'भाषा', heroEyebrow:'भारत · नागरिक बुद्धिमत्ता / 01', heroTitle1:'नौकरशाही', heroTitle2:'को स्पष्ट', heroTitle3:'बनाइए।', heroLead:'CivivOS नागरिक समस्या को एक स्पष्ट प्रक्रिया में बदलता है — तर्क, दस्तावेज़, समयसीमा और अगला कदम सामने रहता है।', startCase:'नागरिक केस शुरू करें', continueCase:'पिछला केस जारी रखें', workflowFirst:'प्रक्रिया पहले · साक्ष्य हमेशा', monitor:'लाइव सिस्टम मॉनिटर', monitorText:'केस इंजन समस्या को वर्गीकृत करता है, ड्राफ्ट तैयार करता है, निगरानी करता है और जरूरत पर अपील तैयार करता है।', principle:'CIVIVOS सिद्धांत / 02', principleTitle:'हर नागरिक समस्या की एक स्थिति होनी चाहिए।', principleText:'एक अगला कदम। एक जिम्मेदार प्राधिकरण। और ऐसा रिकॉर्ड जो गायब न हो।', how:'CIVIVOS कैसे काम करता है / 03', howTitle:'शिकायत से नागरिक कार्रवाई तक।', howText:'CivivOS आपकी शिकायत को ट्रैक करने योग्य प्रक्रिया में बदलता है।', steps:['समस्या बताएं','समस्या वर्गीकृत करें','सही मार्ग चुनें','दस्तावेज़ तैयार करें','समयसीमा देखें','जरूरत पर अपील करें'], intelligence:'CIVIVOS / बुद्धिमत्ता', intelligenceTitle:'सरकारी प्रक्रिया को समझने योग्य बनाएं।', intelligenceText:'सिस्टम शिकायत का विश्लेषण करता है, मार्ग तैयार करता है और केस की स्थिति दिखाता रहता है।', understand:'सिस्टम समझें', newCaseKicker:'नई शिकायत / 01', newCaseTitle:'CivivOS को बताएं क्या हुआ।', newCaseIntro:'समस्या को अपने शब्दों में बताएं। CivivOS इसे वर्गीकृत करेगा और अगली कार्रवाई तैयार करेगा।', citizenName:'नागरिक का नाम', whatHappened:'क्या हुआ?', namePlaceholder:'आपका नाम', complaintPlaceholder:'देरी, इनकार, सेवा न मिलने या अनुत्तरित आवेदन का वर्णन करें…', persistent:'आपका केस एक स्थायी नागरिक रिकॉर्ड बनेगा।', createCase:'केस बनाएं', analyzing:'विश्लेषण…', approve:'ड्राफ्ट स्वीकृत करें', file:'केस दाखिल करें', monitorResponse:'निगरानी शुरू करें', runWatcher:'वॉचर चलाएं', openAppeal:'पहली अपील खोलें', firstAppealReady:'पहली अपील तैयार है।', firstAppealNotReady:'पहली अपील अभी तैयार नहीं है।', returnCase:'केस पर लौटें', systemActive:'सिस्टम सक्रिय', india:'भारत', attention:'ध्यान दें', needsAttention:'आपका अगला निर्णय', noneAttention:'अभी आपकी कार्रवाई की आवश्यकता नहीं है।', activeCases:'सक्रिय मामले', needsAction:'आपकी कार्रवाई आवश्यक', governmentReview:'सरकारी समीक्षा में', yourCases:'आपके मामले', everyMatter:'हर मामला। एक स्पष्ट रास्ता।', doing:'CIVIVOS अभी क्या कर रहा है', doingTitle:'सिस्टम दाखिल करने के बाद भी नहीं रुकता।', responseWatch:'प्रतिक्रिया निगरानी', nextDeadline:'आपकी अगली समयसीमा', noActiveDeadline:'कोई सक्रिय समयसीमा नहीं है।'};
const ta = {...base, command:'கட்டுப்பாடு', dashboard:'டாஷ்போர்டு', newCase:'புதிய வழக்கு', cases:'வழக்குகள்', appeals:'மேல்முறையீடுகள்', active:'அமைப்பு செயல்பாட்டில்', language:'மொழி', heroEyebrow:'இந்தியா · குடிமக்கள் நுண்ணறிவு / 01', heroTitle1:'நிர்வாகத்தை', heroTitle2:'தெளிவாக', heroTitle3:'மாற்றுங்கள்.', heroLead:'CivivOS குடிமக்கள் பிரச்சினையை தெளிவான செயல்முறையாக மாற்றுகிறது.', startCase:'வழக்கை தொடங்குங்கள்', continueCase:'கடைசி வழக்கை தொடருங்கள்', workflowFirst:'செயல்முறை முதலில் · ஆதாரம் எப்போதும்', monitor:'நேரடி அமைப்பு கண்காணிப்பு', monitorText:'கேஸ் எஞ்சின் பிரச்சினையை வகைப்படுத்தி, ஆவணம் தயாரித்து, காலக்கெடுவை கண்காணித்து, தேவைப்பட்டால் மேல்முறையீட்டை தயார் செய்கிறது.', principle:'CIVIVOS கொள்கை / 02', principleTitle:'ஒவ்வொரு குடிமக்கள் பிரச்சினைக்கும் ஒரு நிலை இருக்க வேண்டும்.', principleText:'அடுத்த நடவடிக்கை. பொறுப்பான அதிகாரம். மறையாத பதிவு.', how:'CIVIVOS எப்படி செயல்படுகிறது / 03', howTitle:'புகாரிலிருந்து குடிமக்கள் நடவடிக்கைக்கு.', howText:'CivivOS உங்கள் புகாரை கண்காணிக்கக்கூடிய செயல்முறையாக மாற்றுகிறது.', steps:['பிரச்சினையை கூறுங்கள்','சிக்கலை வகைப்படுத்துங்கள்','சரியான பாதையைத் தேர்வுசெய்யுங்கள்','ஆவணத்தைத் தயாரிக்குங்கள்','காலக்கெடுவை கண்காணியுங்கள்','தேவைப்பட்டால் மேல்முறையீடு செய்யுங்கள்'], newCaseKicker:'புதிய வழக்கு / 01', newCaseTitle:'என்ன நடந்தது என்பதை CivivOS-க்கு சொல்லுங்கள்.', newCaseIntro:'சிக்கலை உங்கள் சொற்களில் விவரிக்கவும்.', citizenName:'குடிமகன் பெயர்', whatHappened:'என்ன நடந்தது?', namePlaceholder:'உங்கள் பெயர்', complaintPlaceholder:'தாமதம், மறுப்பு, சேவை கிடைக்காதது அல்லது பதில் வராத விண்ணப்பத்தை விவரிக்கவும்…', createCase:'வழக்கை உருவாக்குங்கள்', analyzing:'ஆய்வு…', approve:'வரைவை அங்கீகரிக்கவும்', file:'வழக்கை தாக்கல் செய்யவும்', monitorResponse:'கண்காணிப்பை தொடங்கவும்', runWatcher:'கண்காணிப்பை இயக்கவும்', openAppeal:'முதல் மேல்முறையீட்டை திறக்கவும்', firstAppealReady:'முதல் மேல்முறையீடு தயாராக உள்ளது.', firstAppealNotReady:'முதல் மேல்முறையீடு இன்னும் தயாராகவில்லை.', returnCase:'வழக்கிற்கு திரும்புங்கள்', systemActive:'அமைப்பு செயல்பாட்டில்', india:'இந்தியா', attention:'கவனம்', needsAttention:'உங்கள் அடுத்த முடிவு', noneAttention:'இப்போது உங்கள் நடவடிக்கை தேவையில்லை.', activeCases:'செயலில் உள்ள வழக்குகள்', needsAction:'உங்கள் நடவடிக்கை தேவை', governmentReview:'அரசு ஆய்வில்', yourCases:'உங்கள் வழக்குகள்', everyMatter:'ஒவ்வொரு வழக்கும். ஒரு தெளிவான பாதை.', doing:'CIVIVOS என்ன செய்கிறது', doingTitle:'தாக்கல் செய்தவுடன் அமைப்பு நிற்காது.', responseWatch:'பதில் கண்காணிப்பு', nextDeadline:'உங்கள் அடுத்த காலக்கெடு', noActiveDeadline:'செயலில் காலக்கெடு இல்லை.'};
const te = {...base, command:'కమాండ్', dashboard:'డాష్‌బోర్డ్', newCase:'కొత్త కేసు', cases:'కేసులు', appeals:'అప్పీలు', active:'సిస్టమ్ యాక్టివ్', language:'భాష', heroEyebrow:'భారతదేశం · పౌర నిఘా / 01', heroTitle1:'నౌకరశాహిత్యాన్ని', heroTitle2:'స్పష్టంగా', heroTitle3:'చేయండి.', heroLead:'CivivOS పౌర సమస్యను స్పష్టమైన వర్క్‌ఫ్లోగా మార్చుతుంది.', startCase:'పౌర కేసు ప్రారంభించండి', continueCase:'చివరి కేసును కొనసాగించండి', workflowFirst:'వర్క్‌ఫ్లో ముందుగా · ఆధారం ఎల్లప్పుడూ', monitor:'లైవ్ సిస్టమ్ మానిటర్', monitorText:'కేస్ ఇంజిన్ సమస్యను వర్గీకరిస్తుంది, పత్రాన్ని సిద్ధం చేస్తుంది, గడువును పర్యవేక్షిస్తుంది మరియు అవసరమైతే అప్పీల్‌ను సిద్ధం చేస్తుంది.', principle:'CIVIVOS సూత్రం / 02', principleTitle:'ప్రతి పౌర సమస్యకు ఒక స్థితి ఉండాలి.', principleText:'తదుపరి చర్య. బాధ్యతగల అధికారం. మాయంకాని రికార్డు.', how:'CIVIVOS ఎలా పనిచేస్తుంది / 03', howTitle:'ఫిర్యాదు నుంచి పౌర చర్య వరకు.', howText:'CivivOS మీ ఫిర్యాదును ట్రాక్ చేయగల వర్క్‌ఫ్లోగా మార్చుతుంది.', steps:['సమస్యను వివరించండి','సమస్యను వర్గీకరించండి','సరైన మార్గాన్ని ఎంచుకోండి','పత్రాన్ని సిద్ధం చేయండి','గడువును గమనించండి','అవసరమైతే అప్పీల్ చేయండి'], newCaseKicker:'కొత్త కేసు / 01', newCaseTitle:'ఏమి జరిగిందో CivivOSకి చెప్పండి.', newCaseIntro:'సమస్యను మీ మాటల్లో వివరించండి.', citizenName:'పౌరుడి పేరు', whatHappened:'ఏమి జరిగింది?', namePlaceholder:'మీ పేరు', complaintPlaceholder:'ఆలస్యం, తిరస్కరణ, సేవల లోపం లేదా స్పందన లేని దరఖాస్తును వివరించండి…', createCase:'కేసు సృష్టించండి', analyzing:'విశ్లేషణ…', approve:'డ్రాఫ్ట్ ఆమోదించండి', file:'కేసు దాఖలు చేయండి', monitorResponse:'పర్యవేక్షణ ప్రారంభించండి', runWatcher:'వాచర్ నడపండి', openAppeal:'మొదటి అప్పీల్ తెరవండి', firstAppealReady:'మొదటి అప్పీల్ సిద్ధంగా ఉంది.', firstAppealNotReady:'మొదటి అప్పీల్ ఇంకా సిద్ధంగా లేదు.', returnCase:'కేసుకు తిరిగి వెళ్లండి', systemActive:'సిస్టమ్ యాక్టివ్', india:'భారతదేశం', attention:'శ్రద్ధ', needsAttention:'మీ తదుపరి నిర్ణయం', noneAttention:'ప్రస్తుతం మీ చర్య అవసరం లేదు.', activeCases:'సక్రియ కేసులు', needsAction:'మీ చర్య అవసరం', governmentReview:'ప్రభుత్వ సమీక్షలో', yourCases:'మీ కేసులు', everyMatter:'ప్రతి కేసు. ఒక స్పష్టమైన మార్గం.', doing:'CIVIVOS ఏమి చేస్తోంది', doingTitle:'దాఖలు చేసిన తర్వాత కూడా సిస్టమ్ ఆగదు.', responseWatch:'ప్రతిస్పందన పర్యవేక్షణ', nextDeadline:'మీ తదుపరి గడువు', noActiveDeadline:'క్రియాశీల గడువు లేదు.'};
const bn={...base,command:'কমান্ড',dashboard:'ড্যাশবোর্ড',newCase:'নতুন কেস',cases:'কেস',appeals:'আপিল',active:'সিস্টেম সক্রিয়',language:'ভাষা'};
const mr={...base,command:'कमांड',dashboard:'डॅशबोर्ड',newCase:'नवीन प्रकरण',cases:'प्रकरणे',appeals:'अपील',active:'सिस्टम सक्रिय',language:'भाषा'};
const kn={...base,command:'ಕಮಾಂಡ್',dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',newCase:'ಹೊಸ ಪ್ರಕರಣ',cases:'ಪ್ರಕರಣಗಳು',appeals:'ಮೇಲ್ಮನವಿಗಳು',active:'ಸಿಸ್ಟಮ್ ಸಕ್ರಿಯ',language:'ಭಾಷೆ'};
const ml={...base,command:'കമാൻഡ്',dashboard:'ഡാഷ്ബോർഡ്',newCase:'പുതിയ കേസ്',cases:'കേസുകൾ',appeals:'അപ്പീലുകൾ',active:'സിസ്റ്റം സജീവം',language:'ഭാഷ'};

const dictionaries={en:base,hi,ta,te,bn,mr,kn,ml};
const Ctx=createContext(null);
export function I18nProvider({children}){const[language,setLanguage]=useState(()=>localStorage.getItem('civivos:language')||'en'); const value=useMemo(()=>({language,languages:LANGUAGES,setLanguage:(l)=>{const next=dictionaries[l]?l:'en';localStorage.setItem('civivos:language',next);setLanguage(next)},t:dictionaries[language]||base}),[language]); return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useI18n(){const value=useContext(Ctx); if(!value) throw new Error('useI18n must be inside I18nProvider'); return value;}
